# Generated by Django 6.0.2 on 2026-05-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couples", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="couple",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("broken", "Broken"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BreakupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmed_breakups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakup_requests",
                        to="couples.couple",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_breakups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner1_email", models.CharField(max_length=255)),
                ("partner2_email", models.CharField(max_length=255)),
                ("relationship_start", models.DateTimeField()),
                ("relationship_end", models.DateTimeField(auto_now_add=True)),
                ("total_days", models.IntegerField()),
                ("final_loyalty_score", models.IntegerField()),
                ("final_trust_tier", models.CharField(max_length=20)),
                ("breakup_reason", models.TextField(null=True)),
                ("can_reactivate_until", models.DateTimeField()),
                ("is_permanently_reset", models.BooleanField(default=False)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="couples.couple",
                    ),
                ),
            ],
        ),
    ]
