# Generated by Django 6.0.2 on 2026-05-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("couples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Bronze", "Bronze"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Platinum", "Platinum"),
                        ],
                        default="Bronze",
                        max_length=20,
                    ),
                ),
                ("days_together", models.IntegerField(default=0)),
                ("mutual_checkins", models.IntegerField(default=0)),
                ("milestones_achieved", models.IntegerField(default=0)),
                ("missed_checkins", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "couple",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_score",
                        to="couples.couple",
                    ),
                ),
            ],
        ),
    ]
