# Generated by Django 6.0.2 on 2026-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust_scores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustscore",
            name="is_frozen",
            field=models.BooleanField(default=False),
        ),
    ]
