# Generated by Django 6.0.4 on 2026-05-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couples", "0001_initial"),
        ("users", "0003_passwordresetotp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="trust_score",
            new_name="loyalty_score",
        ),
        migrations.AddField(
            model_name="user",
            name="couple",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="couples.couple",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
